.TH QMK 1 "16 Oct 2014"
.SH NAME
qmk \- Make POSIX message queue
.SH SYNOPSIS
.B qmk
[-h|-n]
[-m
.I NUM
]
.I QUEUE
.SH DESCRIPTION
.B qmk
is a command to make a POSIX message queue on a Linux system. The queue
has priorities, is message oriented, and its buffering is managed by the kernel.
.B qmk
takes one argument, a queue name
.I QUEUE.
It must start with "/", like a path.
.P
By default,
.B qmk
will exit successfully if the queue already exists.
.SS OPTIONS
.TP
.B \-h
Print online help.
.TP
.B \-n
Exit with error code 3 if
.I QUEUE
already exists.
.TP
.B "\-m \fINUM\fP"
Make
.I QUEUE
with ability to hold
.I NUM
messages. See
.B /proc/sys/fs/mqueue/msg_max
for the maximum this can be set to. This defaults to 10.
.SH SEE ALSO
qrm(1), qsend(1), qrecv(1), mq_overview(7)
.SH BUGS
Probably.
.SH AUTHORS
Hank Donnay <hank@code42.com>
